version: "3"

services:
  openeducat11:
    image: asperitus/openeducat:11.0
    container_name: openeducat
    environment:
      - DB_PORT_5432_TCP_ADDR=postgres
      - DB_ENV_POSTGRES_USER=openeducat
      - DB_ENV_POSTGRES_PASSWORD=openeducat
    ports:
      - "8069:8069"
      - "8071:8071"
    depends_on:
      - "postgres"
    networks:
      - openeducat-net

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=openeducat
      - POSTGRES_PASSWORD=openeducat
      - POSTGRES_DB=openeducat
    ports:
      - "5432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - openeducat-net

volumes:
  pg-data:

networks:
  openeducat-net:
